version: 2

sources:
  - name: github
    tables:
      - name: ASSET
      - name: BRANCH_COMMIT_RELATION
      - name: COMMIT
      - name: COMMIT_FILE
      - name: COMMIT_PARENT
      - name: COMMIT_PULL_REQUEST
      - name: DEPLOYMENT
      - name: DEPLOYMENT_STATUS
      - name: ISSUE
      - name: ISSUE_ASSIGNEE
      - name: ISSUE_ASSIGNEE_HISTORY
      - name: ISSUE_CLOSED_HISTORY
      - name: ISSUE_COMMENT
      - name: ISSUE_LABEL
      - name: ISSUE_LABEL_HISTORY
      - name: ISSUE_MENTION
      - name: ISSUE_MERGED
      - name: ISSUE_MILESTONE_HISTORY
      - name: ISSUE_REFERENCED
      - name: ISSUE_RENAMED
      - name: LABEL
      - name: MILESTONE
      - name: PULL_REQUEST
      - name: PULL_REQUEST_READY_FOR_REVIEW_HISTORY
      - name: PULL_REQUEST_REVIEW
      - name: PULL_REQUEST_REVIEW_COMMENTS
      - name: PULL_REQUEST_REVIEW_DISMISSED
      - name: RELEASE
      - name: REPOSITORY
      - name: REPOSITORY_TOPIC
      - name: REPO_TEAM
      - name: REQUESTED_REVIEWER_HISTORY
      - name: SECURITY_ADVISORY
      - name: SECURITY_ADVISORY_CWE
      - name: SECURITY_ADVISORY_VULNERABILITY
      - name: SECURITY_ALERT
      - name: SECURITY_CWE
      - name: SECURITY_REFERENCE
      - name: SECURITY_VULNERABILITY
      - name: STARGAZER
      - name: TEAM
      - name: TEAM_MEMBERSHIP
      - name: USER
      - name: USER_EMAIL
      - name: WORKFLOW
      - name: WORKFLOW_RUN
      - name: WORKFLOW_RUN_PULL_REQUEST
